In [2]:
from pathlib import Path
import sqlite3

# Carpeta donde guardaremos la base de datos del Día 3.
CARPETA_DATOS = Path("datos_dia_03")
CARPETA_DATOS.mkdir(exist_ok=True)

# Ruta del archivo de base de datos.
RUTA_DB = CARPETA_DATOS / "ventas.db"

print("Carpeta de trabajo:")
print(CARPETA_DATOS.resolve())

print("\nArchivo de base de datos:")
print(RUTA_DB.resolve())

Carpeta de trabajo:
C:\Users\alumn\OneDrive\Escritorio\Cursos 2026-02\Persistencia de datos con python\Códigos\notebooks\datos_dia_03

Archivo de base de datos:
C:\Users\alumn\OneDrive\Escritorio\Cursos 2026-02\Persistencia de datos con python\Códigos\notebooks\datos_dia_03\ventas.db

In [3]:
import sqlite3

# sqlite3.connect crea el archivo .db si no existe.
conexion = sqlite3.connect(RUTA_DB)

print("Conexión creada correctamente.")
print("Si el archivo no existía, SQLite lo creó automáticamente.")
print(f"Base de datos: {RUTA_DB.resolve()}")

# Cerramos la conexión para liberar el archivo.
conexion.close()

print("Conexión cerrada correctamente.")

Conexión creada correctamente.
Si el archivo no existía, SQLite lo creó automáticamente.
Base de datos: C:\Users\alumn\OneDrive\Escritorio\Cursos 2026-02\Persistencia de datos con python\Códigos\notebooks\datos_dia_03\ventas.db
Conexión cerrada correctamente.

In [4]:
if RUTA_DB.exists():
    print("El archivo ventas.db existe.")
    print(f"Ruta completa: {RUTA_DB.resolve()}")
    print(f"Tamaño del archivo en bytes: {RUTA_DB.stat().st_size}")
else:
    print("El archivo ventas.db no existe todavía.")

El archivo ventas.db existe.
Ruta completa: C:\Users\alumn\OneDrive\Escritorio\Cursos 2026-02\Persistencia de datos con python\Códigos\notebooks\datos_dia_03\ventas.db
Tamaño del archivo en bytes: 12288

In [4]:
conexion = sqlite3.connect(RUTA_DB)
cursor = conexion.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS productos (
    id_producto INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL,
    precio REAL NOT NULL,
    stock INTEGER NOT NULL
)
""")

conexion.commit()
conexion.close()

print("Tabla productos creada correctamente.")

Tabla productos creada correctamente.

In [5]:
conexion = sqlite3.connect(RUTA_DB)
cursor = conexion.cursor()

cursor.execute("""
PRAGMA table_info(productos)
""")

estructura = cursor.fetchall()

conexion.close()

print("Estructura de la tabla productos:")
print("-" * 70)

for columna in estructura:
    print(columna)

Estructura de la tabla productos:
----------------------------------------------------------------------
(0, 'id_producto', 'INTEGER', 0, None, 1)
(1, 'nombre', 'TEXT', 1, None, 0)
(2, 'precio', 'REAL', 1, None, 0)
(3, 'stock', 'INTEGER', 1, None, 0)

In [7]:
import pandas as pd
conexion = sqlite3.connect(RUTA_DB)

estructura_productos = pd.read_sql_query("""
PRAGMA table_info(productos)
""", conexion)

conexion.close()

estructura_productos

   cid         name     type  notnull dflt_value  pk
0    0  id_producto  INTEGER        0       None   1
1    1       nombre     TEXT        1       None   0
2    2       precio     REAL        1       None   0
3    3        stock  INTEGER        1       None   0

In [7]:
conexion = sqlite3.connect(RUTA_DB)
cursor = conexion.cursor()

cursor.execute("""
INSERT INTO productos (nombre, precio, stock)
VALUES (?, ?, ?)
""", ("Mouse inalámbrico", 249.90, 15))

conexion.commit()
conexion.close()

print("Producto insertado correctamente.")

Producto insertado correctamente.

In [ ]:
conexion = sqlite3.connect(RUTA_DB)
cursor = conexion.cursor()

productos = [
    ("Teclado mecánico", 899.00, 8),
    ("Monitor 24 pulgadas", 3299.00, 4),
    ("Cable HDMI", 120.00, 20),
    ("Memoria USB 64GB", 150.00, 30)
]

cursor.executemany("""
INSERT INTO productos (nombre, precio, stock)
VALUES (?, ?, ?)
""", productos)

conexion.commit()
conexion.close()

print("Productos insertados correctamente.")

Productos insertados correctamente.

In [9]:
conexion = sqlite3.connect(RUTA_DB)
cursor = conexion.cursor()

cursor.execute("""
SELECT id_producto, nombre, precio, stock
FROM productos
""")

productos = cursor.fetchall()

conexion.close()

print("Productos registrados:")
print("-" * 70)

for id_producto, nombre, precio, stock in productos:
    print(f"{id_producto} | {nombre} | ${precio:.2f} | Stock: {stock}")

Productos registrados:
----------------------------------------------------------------------
1 | Mouse inalámbrico | $249.90 | Stock: 15
2 | Teclado mecánico | $899.00 | Stock: 8
3 | Monitor 24 pulgadas | $3299.00 | Stock: 4
4 | Cable HDMI | $120.00 | Stock: 20
5 | Memoria USB 64GB | $150.00 | Stock: 30
6 | Mouse inalámbrico | $249.90 | Stock: 15
7 | Mouse inalámbrico | $249.90 | Stock: 15
8 | Teclado mecánico | $899.00 | Stock: 8
9 | Monitor 24 pulgadas | $3299.00 | Stock: 4
10 | Cable HDMI | $120.00 | Stock: 20
11 | Memoria USB 64GB | $150.00 | Stock: 30

In [12]:
conexion = sqlite3.connect(RUTA_DB)
cursor = conexion.cursor()

cursor.execute("""
SELECT id_producto, nombre, precio, stock
FROM productos
WHERE stock < 10 
""")

productos_bajo_stock = cursor.fetchall()

conexion.close()

print("Productos con stock menor a 10:")
print("-" * 70)

for id_producto, nombre, precio, stock in productos_bajo_stock:
    print(f"{id_producto} | {nombre} | ${precio:.2f} | Stock: {stock}")

Productos con stock menor a 10:
----------------------------------------------------------------------
2 | Teclado mecánico | $899.00 | Stock: 8
3 | Monitor 24 pulgadas | $3299.00 | Stock: 4
8 | Teclado mecánico | $899.00 | Stock: 8
9 | Monitor 24 pulgadas | $3299.00 | Stock: 4

In [ ]:
import pandas as pd
conexion = sqlite3.connect(RUTA_DB)

tabla_productos = pd.read_sql_query("""
SELECT id_producto, nombre, precio, stock
FROM productos
ORDER BY precio DESC
""", conexion)

conexion.close()

tabla_productos

    id_producto               nombre  precio  stock
0             3  Monitor 24 pulgadas  3299.0      4
1             9  Monitor 24 pulgadas  3299.0      4
2             2     Teclado mecánico   899.0      8
3             8     Teclado mecánico   899.0      8
4             1    Mouse inalámbrico   249.9     15
5             6    Mouse inalámbrico   249.9     15
6             7    Mouse inalámbrico   249.9     15
7             5     Memoria USB 64GB   150.0     30
8            11     Memoria USB 64GB   150.0     30
9             4           Cable HDMI   120.0     20
10           10           Cable HDMI   120.0     20

In [15]:
conexion = sqlite3.connect(RUTA_DB)
cursor = conexion.cursor()

cursor.execute("""
SELECT name
FROM sqlite_master
WHERE type = 'table'
ORDER BY name
""")

tablas = cursor.fetchall()

conexion.close()

print("Tablas existentes en ventas.db:")
print("-" * 50)

for tabla in tablas:
    print(tabla[0])

Tablas existentes en ventas.db:
--------------------------------------------------
productos
sqlite_sequence