In [1]:
from pathlib import Path
import pandas as pd

CARPETA_DATOS = Path("datos_dia_02")
CARPETA_DATOS.mkdir(exist_ok=True)

print("Carpeta de trabajo lista:")
print(CARPETA_DATOS.resolve())

Carpeta de trabajo lista:
C:\Users\alumn\OneDrive\Escritorio\Cursos 2026-02\Persistencia de datos con python\Códigos\notebooks\datos_dia_02

In [2]:
productos = [
    {
        "id_producto": 1,
        "nombre": "Mouse inalámbrico",
        "precio": 249.90,
        "stock": 15
    },
    {
        "id_producto": 2,
        "nombre": "Teclado mecánico",
        "precio": 899.00,
        "stock": 8
    },
    {
        "id_producto": 3,
        "nombre": "Monitor 24 pulgadas",
        "precio": 3299.00,
        "stock": 4
    }
]

tabla_productos = pd.DataFrame(productos)

tabla_productos

   id_producto               nombre  precio  stock
0            1    Mouse inalámbrico   249.9     15
1            2     Teclado mecánico   899.0      8
2            3  Monitor 24 pulgadas  3299.0      4

In [25]:
print("Nombre conceptual de la tabla: productos")

print("\nCampos de la tabla:")
for campo in tabla_productos.columns:
    print(campo)

print("\nCantidad de registros:")
print(len(tabla_productos))

print("\nPrimer registro de la tabla:")
print(tabla_productos.iloc[1])

Nombre conceptual de la tabla: productos

Campos de la tabla:
id_producto
nombre
precio

Cantidad de registros:
3

Primer registro de la tabla:
id_producto                   2
nombre         Teclado mecánico
precio                    899.0
Name: 1, dtype: object

In [4]:
esquema_productos = {
    "id_producto": "INTEGER, PRIMARY KEY",
    "nombre": "TEXT, NOT NULL",
    "precio": "REAL, NOT NULL",
    "stock": "INTEGER, NOT NULL"
}

print("Esquema conceptual de la tabla productos:")
print("-" * 50)

for campo, definicion in esquema_productos.items():
    print(f"{campo}: {definicion}")

Esquema conceptual de la tabla productos:
--------------------------------------------------
id_producto: INTEGER, PRIMARY KEY
nombre: TEXT, NOT NULL
precio: REAL, NOT NULL
stock: INTEGER, NOT NULL

In [5]:
def validar_llave_primaria(tabla, campo_pk):
    valores = tabla[campo_pk]

    cantidad_total = len(valores)
    cantidad_unicos = valores.nunique()

    if cantidad_total == cantidad_unicos:
        print(f"El campo '{campo_pk}' puede funcionar como llave primaria.")
    else:
        print(f"El campo '{campo_pk}' NO puede funcionar como llave primaria.")
        print("Hay valores repetidos.")

validar_llave_primaria(tabla_productos, "id_producto")

El campo 'id_producto' puede funcionar como llave primaria.

In [ ]:
productos_con_error = [
    {
        "id_producto": 1,
        "nombre": "Mouse inalámbrico",
        "precio": 249.90,
        "stock": 15
    },
    {
        "id_producto": 1,
        "nombre": "Teclado mecánico",
        "precio": 899.00,
        "stock": 8
    },
    {
        "id_producto": 3,
        "nombre": "Monitor 24 pulgadas",
        "precio": 3299.00,
        "stock": 4
    }
]

tabla_productos_error = pd.DataFrame(productos_con_error)

tabla_productos_error

   id_producto               nombre  precio  stock
0            1    Mouse inalámbrico   249.9     15
1            1     Teclado mecánico   899.0      8
2            3  Monitor 24 pulgadas  3299.0      4

In [7]:
validar_llave_primaria(tabla_productos_error, "id_producto")

El campo 'id_producto' NO puede funcionar como llave primaria.
Hay valores repetidos.

In [8]:
duplicados = tabla_productos_error[
    tabla_productos_error.duplicated(subset=["id_producto"], keep=False)
]

print("Registros con llave primaria duplicada:")
duplicados

Registros con llave primaria duplicada:

   id_producto             nombre  precio  stock
0            1  Mouse inalámbrico   249.9     15
1            1   Teclado mecánico   899.0      8

In [31]:
clientes = [
    {
        "id_cliente": 1,
        "nombre": "Ana López",
        "correo": "ana@example.com"
    },
    {
        "id_cliente": 2,
        "nombre": "Carlos Pérez",
        "correo": "carlos@example.com"
    },
    {
        "id_cliente": 3,
        "nombre": "María Torres",
        "correo": "maria@example.com"
    }
]

ventas = [
    {
        "id_venta": 1,
        "id_cliente": 1,
        "fecha": "2026-06-09",
        "total": 499.80
    },
    {
        "id_venta": 2,
        "id_cliente": 2,
        "fecha": "2026-06-09",
        "total": 899.00
    },
    {
        "id_venta": 3,
        "id_cliente": 1,
        "fecha": "2026-06-10",
        "total": 3299.00
    }
]

tabla_clientes = pd.DataFrame(clientes)
tabla_ventas = pd.DataFrame(ventas)

print("Tabla clientes:")
display(tabla_clientes)

print("Tabla ventas:")
display(tabla_ventas)

Tabla clientes:

   id_cliente        nombre              correo
0           1     Ana López     ana@example.com
1           2  Carlos Pérez  carlos@example.com
2           3  María Torres   maria@example.com

Tabla ventas:

   id_venta  id_cliente       fecha   total
0         1           1  2026-06-09   499.8
1         2           2  2026-06-09   899.0
2         3           1  2026-06-10  3299.0

In [32]:
def validar_llave_foranea(tabla_hija, campo_fk, tabla_padre, campo_pk):
    valores_fk = set(tabla_hija[campo_fk])
    valores_pk = set(tabla_padre[campo_pk])

    valores_invalidos = valores_fk - valores_pk

    if not valores_invalidos:
        print(f"La llave foránea '{campo_fk}' es válida.")
        print("Todas las ventas apuntan a clientes existentes.")
    else:
        print(f"La llave foránea '{campo_fk}' tiene valores inválidos.")
        print("Estos valores no existen en la tabla padre:")
        print(valores_invalidos)

validar_llave_foranea(
    tabla_hija=tabla_ventas,
    campo_fk="id_cliente",
    tabla_padre=tabla_clientes,
    campo_pk="id_cliente"
)

La llave foránea 'id_cliente' es válida.
Todas las ventas apuntan a clientes existentes.

In [ ]:
#Relacion uno a muchos
ventas_por_cliente = tabla_ventas.groupby("id_cliente").size().reset_index(name="cantidad_ventas")

ventas_por_cliente = ventas_por_cliente.merge(
    tabla_clientes,
    on="id_cliente",
    how="left"
)

ventas_por_cliente = ventas_por_cliente[["id_cliente", "nombre", "cantidad_ventas"]]

ventas_por_cliente

   id_cliente        nombre  cantidad_ventas
0           1     Ana López                2
1           2  Carlos Pérez                1

In [15]:
ventas_con_cliente = tabla_ventas.merge(
    tabla_clientes,
    on="id_cliente",
    how="left"
)

ventas_con_cliente = ventas_con_cliente[
    ["id_venta", "fecha", "nombre", "correo", "total"]
]

ventas_con_cliente

   id_venta       fecha        nombre              correo   total
0         1  2026-06-09     Ana López     ana@example.com   499.8
1         2  2026-06-09  Carlos Pérez  carlos@example.com   899.0
2         3  2026-06-10     Ana López     ana@example.com  3299.0

In [ ]:
#Relacion muchos a muchos
productos = [
    {
        "id_producto": 1,
        "nombre": "Mouse inalámbrico",
        "precio": 249.90
    },
    {
        "id_producto": 2,
        "nombre": "Teclado mecánico",
        "precio": 899.00
    },
    {
        "id_producto": 3,
        "nombre": "Monitor 24 pulgadas",
        "precio": 3299.00
    }
]

ventas = [
    {
        "id_venta": 1,
        "id_cliente": 1,
        "fecha": "2026-06-09"
    },
    {
        "id_venta": 2,
        "id_cliente": 2,
        "fecha": "2026-06-10"
    }
]

detalle_ventas = [
    {
        "id_detalle": 1,
        "id_venta": 1,
        "id_producto": 1,
        "cantidad": 2,
        "precio_unitario": 249.90
    },
    {
        "id_detalle": 2,
        "id_venta": 1,
        "id_producto": 2,
        "cantidad": 1,
        "precio_unitario": 899.00
    },
    {
        "id_detalle": 3,
        "id_venta": 2,
        "id_producto": 3,
        "cantidad": 1,
        "precio_unitario": 3299.00
    }
]

tabla_productos = pd.DataFrame(productos)
tabla_ventas_simple = pd.DataFrame(ventas)
tabla_detalle_ventas = pd.DataFrame(detalle_ventas)

print("Tabla productos:")
display(tabla_productos)

print("Tabla ventas:")
display(tabla_ventas_simple)

print("Tabla detalle_ventas:")
display(tabla_detalle_ventas)

Tabla productos:

   id_producto               nombre  precio
0            1    Mouse inalámbrico   249.9
1            2     Teclado mecánico   899.0
2            3  Monitor 24 pulgadas  3299.0

Tabla ventas:

   id_venta  id_cliente       fecha
0         1           1  2026-06-09
1         2           2  2026-06-10

Tabla detalle_ventas:

   id_detalle  id_venta  id_producto  cantidad  precio_unitario
0           1         1            1         2            249.9
1           2         1            2         1            899.0
2           3         2            3         1           3299.0

In [17]:
tabla_detalle_ventas["subtotal"] = (
    tabla_detalle_ventas["cantidad"] * tabla_detalle_ventas["precio_unitario"]
)

tabla_detalle_ventas

   id_detalle  id_venta  id_producto  cantidad  precio_unitario  subtotal
0           1         1            1         2            249.9     499.8
1           2         1            2         1            899.0     899.0
2           3         2            3         1           3299.0    3299.0

In [18]:
detalle_con_productos = tabla_detalle_ventas.merge(
    tabla_productos,
    on="id_producto",
    how="left"
)

detalle_con_productos = detalle_con_productos[
    [
        "id_detalle",
        "id_venta",
        "id_producto",
        "nombre",
        "cantidad",
        "precio_unitario",
        "subtotal"
    ]
]

detalle_con_productos

,id_detalle,id_venta,id_producto,nombre,cantidad,precio_unitario,subtotal
0,1,1,1,Mouse inalámbrico,2,249.9,499.8
1,2,1,2,Teclado mecánico,1,899.0,899.0
2,3,2,3,Monitor 24 pulgadas,1,3299.0,3299.0

In [19]:
total_por_venta = tabla_detalle_ventas.groupby("id_venta")["subtotal"].sum().reset_index()

total_por_venta = total_por_venta.rename(columns={"subtotal": "total_venta"})

total_por_venta

   id_venta  total_venta
0         1       1398.8
1         2       3299.0

In [ ]:
esquema_sistema_ventas = {
    "clientes": {
        "id_cliente": "INTEGER, PRIMARY KEY",
        "nombre": "TEXT, NOT NULL",
        "correo": "TEXT, UNIQUE"
    },
    "productos": {
        "id_producto": "INTEGER, PRIMARY KEY",
        "nombre": "TEXT, NOT NULL",
        "precio": "REAL, NOT NULL",
        "stock": "INTEGER, NOT NULL"
    },
    "ventas": {
        "id_venta": "INTEGER, PRIMARY KEY",
        "id_cliente": "INTEGER, FOREIGN KEY -> clientes.id_cliente",
        "fecha": "TEXT, NOT NULL"
    },
    "detalle_ventas": {
        "id_detalle": "INTEGER, PRIMARY KEY",
        "id_venta": "INTEGER, FOREIGN KEY -> ventas.id_venta",
        "id_producto": "INTEGER, FOREIGN KEY -> productos.id_producto",
        "cantidad": "INTEGER, NOT NULL",
        "precio_unitario": "REAL, NOT NULL"
    }
}

for tabla, campos in esquema_sistema_ventas.items():
    print(f"\nTabla: {tabla}")
    print("-" * 50)

    for campo, definicion in campos.items():
        print(f"{campo}: {definicion}")

Tabla: clientes
--------------------------------------------------
id_cliente: INTEGER, PRIMARY KEY
nombre: TEXT, NOT NULL
correo: TEXT, UNIQUE

Tabla: productos
--------------------------------------------------
id_producto: INTEGER, PRIMARY KEY
nombre: TEXT, NOT NULL
precio: REAL, NOT NULL
stock: INTEGER, NOT NULL

Tabla: ventas
--------------------------------------------------
id_venta: INTEGER, PRIMARY KEY
id_cliente: INTEGER, FOREIGN KEY -> clientes.id_cliente
fecha: TEXT, NOT NULL

Tabla: detalle_ventas
--------------------------------------------------
id_detalle: INTEGER, PRIMARY KEY
id_venta: INTEGER, FOREIGN KEY -> ventas.id_venta
id_producto: INTEGER, FOREIGN KEY -> productos.id_producto
cantidad: INTEGER, NOT NULL
precio_unitario: REAL, NOT NULL

In [21]:
relaciones = [
    {
        "tabla_origen": "ventas",
        "campo_origen": "id_cliente",
        "tabla_destino": "clientes",
        "campo_destino": "id_cliente",
        "tipo": "Muchos a uno"
    },
    {
        "tabla_origen": "detalle_ventas",
        "campo_origen": "id_venta",
        "tabla_destino": "ventas",
        "campo_destino": "id_venta",
        "tipo": "Muchos a uno"
    },
    {
        "tabla_origen": "detalle_ventas",
        "campo_origen": "id_producto",
        "tabla_destino": "productos",
        "campo_destino": "id_producto",
        "tipo": "Muchos a uno"
    }
]

tabla_relaciones = pd.DataFrame(relaciones)

tabla_relaciones

     tabla_origen campo_origen tabla_destino campo_destino          tipo
0          ventas   id_cliente      clientes    id_cliente  Muchos a uno
1  detalle_ventas     id_venta        ventas      id_venta  Muchos a uno
2  detalle_ventas  id_producto     productos   id_producto  Muchos a uno

In [22]:
ventas_tabla_unica = [
    {
        "id_venta": 1,
        "fecha": "2026-06-09",
        "cliente": "Ana López",
        "correo": "ana@example.com",
        "producto": "Mouse inalámbrico",
        "cantidad": 2,
        "precio_unitario": 249.90
    },
    {
        "id_venta": 1,
        "fecha": "2026-06-09",
        "cliente": "Ana López",
        "correo": "ana@example.com",
        "producto": "Teclado mecánico",
        "cantidad": 1,
        "precio_unitario": 899.00
    },
    {
        "id_venta": 2,
        "fecha": "2026-06-10",
        "cliente": "Carlos Pérez",
        "correo": "carlos@example.com",
        "producto": "Monitor 24 pulgadas",
        "cantidad": 1,
        "precio_unitario": 3299.00
    }
]

tabla_unica = pd.DataFrame(ventas_tabla_unica)

tabla_unica

,id_venta,fecha,cliente,correo,producto,cantidad,precio_unitario
0,1,2026-06-09,Ana López,ana@example.com,Mouse inalámbrico,2,249.9
1,1,2026-06-09,Ana López,ana@example.com,Teclado mecánico,1,899.0
2,2,2026-06-10,Carlos Pérez,carlos@example.com,Monitor 24 pulgadas,1,3299.0

In [23]:
conteo_clientes = tabla_unica["cliente"].value_counts().reset_index()
conteo_clientes.columns = ["cliente", "veces_repetido"]

conteo_clientes

        cliente  veces_repetido
0     Ana López               2
1  Carlos Pérez               1

In [24]:
import pandas as pd

clientes = pd.DataFrame([
    {"id_cliente": 1, "nombre": "Ana López", "correo": "ana@example.com"},
    {"id_cliente": 2, "nombre": "Carlos Pérez", "correo": "carlos@example.com"}
])

productos = pd.DataFrame([
    {"id_producto": 1, "nombre": "Mouse inalámbrico", "precio": 249.90, "stock": 15},
    {"id_producto": 2, "nombre": "Teclado mecánico", "precio": 899.00, "stock": 8},
    {"id_producto": 3, "nombre": "Monitor 24 pulgadas", "precio": 3299.00, "stock": 4}
])

ventas = pd.DataFrame([
    {"id_venta": 1, "id_cliente": 1, "fecha": "2026-06-09"},
    {"id_venta": 2, "id_cliente": 2, "fecha": "2026-06-10"}
])

detalle_ventas = pd.DataFrame([
    {"id_detalle": 1, "id_venta": 1, "id_producto": 1, "cantidad": 2, "precio_unitario": 249.90},
    {"id_detalle": 2, "id_venta": 1, "id_producto": 2, "cantidad": 1, "precio_unitario": 899.00},
    {"id_detalle": 3, "id_venta": 2, "id_producto": 3, "cantidad": 1, "precio_unitario": 3299.00}
])

detalle_ventas["subtotal"] = detalle_ventas["cantidad"] * detalle_ventas["precio_unitario"]

ventas_con_cliente = ventas.merge(clientes, on="id_cliente", how="left")

detalle_con_producto = detalle_ventas.merge(productos, on="id_producto", how="left")

total_por_venta = detalle_ventas.groupby("id_venta")["subtotal"].sum().reset_index()
total_por_venta = total_por_venta.rename(columns={"subtotal": "total"})

resumen_ventas = ventas_con_cliente.merge(total_por_venta, on="id_venta", how="left")

print("Clientes")
display(clientes)

print("Productos")
display(productos)

print("Ventas")
display(ventas)

print("Detalle de ventas")
display(detalle_ventas)

print("Ventas con nombre de cliente")
display(resumen_ventas[["id_venta", "fecha", "nombre", "correo", "total"]])

print("Detalle con nombre de producto")
display(detalle_con_producto[[
    "id_venta",
    "nombre",
    "cantidad",
    "precio_unitario",
    "subtotal"
]])

Clientes

   id_cliente        nombre              correo
0           1     Ana López     ana@example.com
1           2  Carlos Pérez  carlos@example.com

Productos

   id_producto               nombre  precio  stock
0            1    Mouse inalámbrico   249.9     15
1            2     Teclado mecánico   899.0      8
2            3  Monitor 24 pulgadas  3299.0      4

Ventas

   id_venta  id_cliente       fecha
0         1           1  2026-06-09
1         2           2  2026-06-10

Detalle de ventas

   id_detalle  id_venta  id_producto  cantidad  precio_unitario  subtotal
0           1         1            1         2            249.9     499.8
1           2         1            2         1            899.0     899.0
2           3         2            3         1           3299.0    3299.0

Ventas con nombre de cliente

   id_venta       fecha        nombre              correo   total
0         1  2026-06-09     Ana López     ana@example.com  1398.8
1         2  2026-06-10  Carlos Pérez  carlos@example.com  3299.0

Detalle con nombre de producto

   id_venta               nombre  cantidad  precio_unitario  subtotal
0         1    Mouse inalámbrico         2            249.9     499.8
1         1     Teclado mecánico         1            899.0     899.0
2         2  Monitor 24 pulgadas         1           3299.0    3299.0