In [1]:
from pathlib import Path
import sqlite3
import pandas as pd

# Carpeta del Día 4.
CARPETA_DATOS = Path("datos_dia_04")
CARPETA_DATOS.mkdir(exist_ok=True)

# Base de datos que se usará durante esta sesión.
RUTA_DB = CARPETA_DATOS / "ventas_dia_04.db"

print("Carpeta de trabajo:")
print(CARPETA_DATOS.resolve())

print("\nBase de datos del Día 4:")
print(RUTA_DB.resolve())

Carpeta de trabajo:
C:\Users\alumn\OneDrive\Escritorio\Cursos 2026-02\Persistencia de datos con python\Códigos\notebooks\datos_dia_04

Base de datos del Día 4:
C:\Users\alumn\OneDrive\Escritorio\Cursos 2026-02\Persistencia de datos con python\Códigos\notebooks\datos_dia_04\ventas_dia_04.db

In [2]:
conexion = sqlite3.connect(RUTA_DB)

print("Conexión creada correctamente.")
print("Si la base no existía, SQLite creó el archivo ventas_dia_04.db.")

conexion.close()

print("Conexión cerrada correctamente.")

Conexión creada correctamente.
Si la base no existía, SQLite creó el archivo ventas_dia_04.db.
Conexión cerrada correctamente.

In [ ]:
conexion = sqlite3.connect(RUTA_DB)
cursor = conexion.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS productos (
    id_producto INTEGER PRIMARY KEY AUTOINCREMENT,
    sku TEXT NOT NULL UNIQUE,
    nombre TEXT NOT NULL,
    precio REAL NOT NULL CHECK(precio > 0),
    stock INTEGER NOT NULL DEFAULT 0 CHECK(stock >= 0),
    categoria TEXT DEFAULT 'General'
)
""")

conexion.commit()
conexion.close()

print("Tabla productos creada correctamente.")

Tabla productos creada correctamente.

In [4]:
conexion = sqlite3.connect(RUTA_DB)

estructura_productos = pd.read_sql_query("""
PRAGMA table_info(productos)
""", conexion)

conexion.close()

estructura_productos

   cid         name     type  notnull dflt_value  pk
0    0  id_producto  INTEGER        0        NaN   1
1    1          sku     TEXT        1        NaN   0
2    2       nombre     TEXT        1        NaN   0
3    3       precio     REAL        1        NaN   0
4    4        stock  INTEGER        1          0   0
5    5    categoria     TEXT        0  'General'   0

In [ ]:
conexion = sqlite3.connect(RUTA_DB)
cursor = conexion.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS tipos_datos_demo (
    id_demo INTEGER PRIMARY KEY AUTOINCREMENT,
    dato_entero INTEGER,
    dato_decimal REAL,
    dato_texto TEXT,
    dato_nulo NULL
)
""")

conexion.commit()
conexion.close()

print("Tabla tipos_datos_demo creada correctamente.")

Tabla tipos_datos_demo creada correctamente.

In [7]:
conexion = sqlite3.connect(RUTA_DB)
cursor = conexion.cursor()

cursor.execute("""
INSERT INTO tipos_datos_demo (
    dato_entero,
    dato_decimal,
    dato_texto,
    dato_nulo
)
VALUES (?, ?, ?, ?)
""", (10, 25.75, "Producto de prueba", None))

conexion.commit()
conexion.close()

print("Registro insertado en tipos_datos_demo.")

Registro insertado en tipos_datos_demo.

In [8]:
conexion = sqlite3.connect(RUTA_DB)

resultado_tipos = pd.read_sql_query("""
SELECT
    id_demo,
    dato_entero,
    typeof(dato_entero) AS tipo_entero,
    dato_decimal,
    typeof(dato_decimal) AS tipo_decimal,
    dato_texto,
    typeof(dato_texto) AS tipo_texto,
    dato_nulo,
    typeof(dato_nulo) AS tipo_nulo
FROM tipos_datos_demo
""", conexion)

conexion.close()

resultado_tipos

,id_demo,dato_entero,tipo_entero,dato_decimal,tipo_decimal,dato_texto,tipo_texto,dato_nulo,tipo_nulo
0,1,10,integer,25.75,real,Producto de prueba,text,None,null
1,2,10,integer,25.75,real,Producto de prueba,text,None,null

In [ ]:
conexion = sqlite3.connect(RUTA_DB)
cursor = conexion.cursor()

cursor.execute("""
INSERT INTO productos (sku, nombre, precio, stock, categoria)
VALUES (?, ?, ?, ?, ?)
""", ("P001", "Mouse inalámbrico", 249.90, 15, "Accesorios"))

conexion.commit()
conexion.close()

print("Producto insertado correctamente.")

IntegrityError: UNIQUE constraint failed: productos.sku

In [12]:
conexion = sqlite3.connect(RUTA_DB)
cursor = conexion.cursor()

productos = [
    ("P002", "Teclado mecánico", 899.00, 8, "Accesorios"),
    ("P003", "Monitor 24 pulgadas", 3299.00, 4, "Pantallas"),
    ("P004", "Cable HDMI", 120.00, 20, "Cables"),
    ("P005", "Memoria USB 64GB", 150.00, 30, "Almacenamiento")
]

cursor.executemany("""
INSERT INTO productos (sku, nombre, precio, stock, categoria)
VALUES (?, ?, ?, ?, ?)
""", productos)

conexion.commit()
conexion.close()

print("Productos insertados correctamente.")

Productos insertados correctamente.

In [13]:
conexion = sqlite3.connect(RUTA_DB)

tabla_productos = pd.read_sql_query("""
SELECT id_producto, sku, nombre, precio, stock, categoria
FROM productos
""", conexion)

conexion.close()

tabla_productos

   id_producto   sku               nombre  precio  stock       categoria
0            1  P001    Mouse inalámbrico   249.9     15      Accesorios
1            2  P002     Teclado mecánico   899.0      8      Accesorios
2            3  P003  Monitor 24 pulgadas  3299.0      4       Pantallas
3            4  P004           Cable HDMI   120.0     20          Cables
4            5  P005     Memoria USB 64GB   150.0     30  Almacenamiento

In [14]:
conexion = sqlite3.connect(RUTA_DB)

consulta_alias = pd.read_sql_query("""
SELECT
    nombre AS producto,
    precio AS precio_venta,
    stock AS unidades_disponibles
FROM productos
""", conexion)

conexion.close()

consulta_alias

              producto  precio_venta  unidades_disponibles
0    Mouse inalámbrico         249.9                    15
1     Teclado mecánico         899.0                     8
2  Monitor 24 pulgadas        3299.0                     4
3           Cable HDMI         120.0                    20
4     Memoria USB 64GB         150.0                    30

In [15]:
conexion = sqlite3.connect(RUTA_DB)

valor_inventario = pd.read_sql_query("""
SELECT
    sku,
    nombre,
    precio,
    stock,
    precio * stock AS valor_total_en_inventario
FROM productos
""", conexion)

conexion.close()

valor_inventario

    sku               nombre  precio  stock  valor_total_en_inventario
0  P001    Mouse inalámbrico   249.9     15                     3748.5
1  P002     Teclado mecánico   899.0      8                     7192.0
2  P003  Monitor 24 pulgadas  3299.0      4                    13196.0
3  P004           Cable HDMI   120.0     20                     2400.0
4  P005     Memoria USB 64GB   150.0     30                     4500.0

In [17]:
conexion = sqlite3.connect(RUTA_DB)
cursor = conexion.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS clientes (
    id_cliente INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL,
    correo TEXT UNIQUE,
    telefono TEXT,
    ciudad TEXT DEFAULT 'No especificada'
)
""")

conexion.commit()
conexion.close()

print("Tabla clientes creada correctamente.")

Tabla clientes creada correctamente.

In [18]:
conexion = sqlite3.connect(RUTA_DB)
cursor = conexion.cursor()

clientes = [
    ("Ana López", "ana@example.com", "555-111-2222", "CDMX"),
    ("Carlos Pérez", "carlos@example.com", None, "Guadalajara"),
    ("María Torres", "maria@example.com", None, None)
]

cursor.executemany("""
INSERT INTO clientes (nombre, correo, telefono, ciudad)
VALUES (?, ?, ?, ?)
""", clientes)

conexion.commit()
conexion.close()

print("Clientes insertados correctamente.")

Clientes insertados correctamente.

In [19]:
conexion = sqlite3.connect(RUTA_DB)

clientes_sin_telefono = pd.read_sql_query("""
SELECT id_cliente, nombre, correo, telefono
FROM clientes
WHERE telefono IS NULL
""", conexion)

conexion.close()

clientes_sin_telefono

   id_cliente        nombre              correo telefono
0           2  Carlos Pérez  carlos@example.com     None
1           3  María Torres   maria@example.com     None

In [20]:
def intentar_insertar_producto(sku, nombre, precio, stock, categoria=None):
    conexion = sqlite3.connect(RUTA_DB)
    cursor = conexion.cursor()

    try:
        cursor.execute("""
        INSERT INTO productos (sku, nombre, precio, stock, categoria)
        VALUES (?, ?, ?, ?, ?)
        """, (sku, nombre, precio, stock, categoria))

        conexion.commit()
        print(f"Producto insertado correctamente: {sku} - {nombre}")

    except sqlite3.IntegrityError as error:
        print("No se pudo insertar el producto.")
        print("Motivo:", error)

    finally:
        conexion.close()

In [21]:
intentar_insertar_producto(
    sku="P001",
    nombre="Mouse repetido",
    precio=300.00,
    stock=5,
    categoria="Accesorios"
)

No se pudo insertar el producto.
Motivo: UNIQUE constraint failed: productos.sku

In [22]:
intentar_insertar_producto(
    sku="P006",
    nombre=None,
    precio=500.00,
    stock=10,
    categoria="Prueba"
)

No se pudo insertar el producto.
Motivo: NOT NULL constraint failed: productos.nombre

In [23]:
intentar_insertar_producto(
    sku="P007",
    nombre="Producto con precio inválido",
    precio=-100.00,
    stock=10,
    categoria="Prueba"
)

No se pudo insertar el producto.
Motivo: CHECK constraint failed: precio > 0

In [24]:
intentar_insertar_producto(
    sku="P008",
    nombre="Producto con stock inválido",
    precio=100.00,
    stock=-3,
    categoria="Prueba"
)

No se pudo insertar el producto.
Motivo: CHECK constraint failed: stock >= 0

In [25]:
conexion = sqlite3.connect(RUTA_DB)
cursor = conexion.cursor()

cursor.execute("""
INSERT INTO productos (sku, nombre, precio, stock)
VALUES (?, ?, ?, ?)
""", ("P009", "Adaptador USB-C", 199.00, 12))

conexion.commit()
conexion.close()

print("Producto insertado sin especificar categoría.")

Producto insertado sin especificar categoría.

In [26]:
conexion = sqlite3.connect(RUTA_DB)

producto_default = pd.read_sql_query("""
SELECT id_producto, sku, nombre, precio, stock, categoria
FROM productos
WHERE sku = 'P009'
""", conexion)

conexion.close()

producto_default

   id_producto   sku           nombre  precio  stock categoria
0            6  P009  Adaptador USB-C   199.0     12   General

In [27]:
from pathlib import Path
import sqlite3
import pandas as pd

CARPETA_DATOS = Path("datos_dia_04")
CARPETA_DATOS.mkdir(exist_ok=True)

RUTA_DB = CARPETA_DATOS / "ventas_dia_04.db"

conexion = sqlite3.connect(RUTA_DB)
cursor = conexion.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS productos (
    id_producto INTEGER PRIMARY KEY AUTOINCREMENT,
    sku TEXT NOT NULL UNIQUE,
    nombre TEXT NOT NULL,
    precio REAL NOT NULL CHECK(precio > 0),
    stock INTEGER NOT NULL DEFAULT 0 CHECK(stock >= 0),
    categoria TEXT DEFAULT 'General'
)
""")

productos = [
    ("P001", "Mouse inalámbrico", 249.90, 15, "Accesorios"),
    ("P002", "Teclado mecánico", 899.00, 8, "Accesorios"),
    ("P003", "Monitor 24 pulgadas", 3299.00, 4, "Pantallas"),
    ("P004", "Cable HDMI", 120.00, 20, "Cables"),
    ("P005", "Memoria USB 64GB", 150.00, 30, "Almacenamiento")
]

for producto in productos:
    try:
        cursor.execute("""
        INSERT INTO productos (sku, nombre, precio, stock, categoria)
        VALUES (?, ?, ?, ?, ?)
        """, producto)
    except sqlite3.IntegrityError:
        pass

conexion.commit()

consulta = pd.read_sql_query("""
SELECT
    id_producto,
    sku,
    nombre,
    precio,
    stock,
    categoria,
    precio * stock AS valor_inventario
FROM productos
ORDER BY precio DESC
""", conexion)

conexion.close()

consulta

,id_producto,sku,nombre,precio,stock,categoria,valor_inventario
0,3,P003,Monitor 24 pulgadas,3299.0,4,Pantallas,13196.0
1,2,P002,Teclado mecánico,899.0,8,Accesorios,7192.0
2,1,P001,Mouse inalámbrico,249.9,15,Accesorios,3748.5
3,6,P009,Adaptador USB-C,199.0,12,General,2388.0
4,5,P005,Memoria USB 64GB,150.0,30,Almacenamiento,4500.0
5,4,P004,Cable HDMI,120.0,20,Cables,2400.0